name: fun_with_dice
description: Nice dice apps

publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  confetti: ^0.7.0
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  package_info_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - images/
